version: '3'
services:
  api:
    image: marquesaline/api-news
    ports:
      - '3000:3000'
    links:
      - link-db
  link-db:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - AUTH=no